export const queryKeys = {
    userTokens: 'userTokens',
    stakedTokenStatus: 'stakedTokenStatus',
    getTokenBalance: 'getTokenBalance',
    tokenNames: 'tokenNames',
    babyTokensStatus: 'babyTokensStatus',
    lore: 'lore',
    name: 'name',
    transfer: 'transfer',
    isStaked: 'isStaked',
    isOwner: 'isOwner',
    babyParent: 'babyParent',
    babyMetaData: 'babyMetaData',
    ladyNumberOfChild: 'ladyNumberOfChild',
    numberOfBreed: 'numberOfBreed',
    rentPrice: 'rentPrice',
    maleRentingBabyPrice: 'maleRentingBabyPrice',
    femaleRentingBabyPrice: 'femaleRentingBabyPrice',
    isApprovedForAll: 'isApprovedForAll',
    getUserRentedNfts: 'getUserRentedNfts',
    getAppTenderNft: 'getAppTenderNft',
    derentOfGenesisAndLadies: 'derentOfGenesisAndLadies',
    // farm
    queryContract: 'queryContract',
    farmIsApprovedForAll: 'farmIsApprovedForAll',
    getBurnRate: 'getBurnRate',
    getDataCollectively: 'getDataCollectively',
    GetUserAssetsData: 'GetUserAssetsData',
    isApprovedForAllStaking: 'isApprovedForAllStaking',
    getPendingBalance: 'getPendingBalance',
    getTokenInfo: 'getTokenInfo',
    multipleStaking:'multipleStaking'/*...*/
};
